/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisador;

import java.io.File;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import static analisador.Lexer.n_column;
import static analisador.Lexer.n_line;


/**
 *
 * @author Marcos Mol
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    
    public JTextArea jText;
    public String fileName = "";
    public String filePath = "";
    public TS tabelaSimbolos;
        
    // metodo executar
    public void executar(String filePath) throws Exception { 
       
        Lexer lexer = new Lexer(tabelaSimbolos, filePath);
        
        // Analise Léxica
        lexer.leituraArquivoToken(textArea2);
        
        // Novo Lexer para a Análise Sintática (Reinicio da leitura do Arquivo
        Lexer newlexer = new Lexer(tabelaSimbolos, filePath);
         
        // Análise Sintática
        Parser parser = new Parser(newlexer, textArea3);
        
        parser.nonRecursiveParser();
        
    }
    
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(this);
        Look.definelook(this);
        //setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnAnexar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAnalisar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea3 = new javax.swing.JTextArea();
        lb_entrada1 = new javax.swing.JLabel();
        lb_analiseLexica1 = new javax.swing.JLabel();
        lb_entrada2 = new javax.swing.JLabel();
        lb_entrada3 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnexar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAnexar.setForeground(new java.awt.Color(153, 0, 51));
        btnAnexar.setText("Anexar Arquivo Javazinho");
        btnAnexar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAnexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnexarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(153, 0, 51));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.MatteBorder(null));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnAnalisar1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAnalisar1.setForeground(new java.awt.Color(153, 0, 51));
        btnAnalisar1.setText("Analisar");
        btnAnalisar1.setBorder(new javax.swing.border.MatteBorder(null));
        btnAnalisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisar1ActionPerformed(evt);
            }
        });

        textArea2.setEditable(false);
        textArea2.setColumns(20);
        textArea2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textArea2.setRows(5);
        jScrollPane2.setViewportView(textArea2);

        textArea3.setEditable(false);
        textArea3.setColumns(20);
        textArea3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textArea3.setRows(5);
        jScrollPane3.setViewportView(textArea3);

        lb_entrada1.setBackground(new java.awt.Color(51, 153, 0));
        lb_entrada1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_entrada1.setForeground(new java.awt.Color(153, 0, 51));
        lb_entrada1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_entrada1.setText("  Nome do Arquivo");
        lb_entrada1.setToolTipText("");
        lb_entrada1.setBorder(new javax.swing.border.MatteBorder(null));
        lb_entrada1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_analiseLexica1.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lb_analiseLexica1.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica1.setText("Compilador");
        lb_analiseLexica1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        lb_entrada2.setBackground(new java.awt.Color(51, 153, 0));
        lb_entrada2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_entrada2.setForeground(new java.awt.Color(153, 0, 51));
        lb_entrada2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_entrada2.setText("Lexer");
        lb_entrada2.setToolTipText("");
        lb_entrada2.setBorder(new javax.swing.border.MatteBorder(null));
        lb_entrada2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_entrada3.setBackground(new java.awt.Color(51, 153, 0));
        lb_entrada3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_entrada3.setForeground(new java.awt.Color(153, 0, 51));
        lb_entrada3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_entrada3.setText("Parser");
        lb_entrada3.setToolTipText("");
        lb_entrada3.setBorder(new javax.swing.border.MatteBorder(null));
        lb_entrada3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_entrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnexar, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnalisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                                    .addComponent(lb_entrada2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                                    .addComponent(lb_entrada3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lb_analiseLexica1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb_analiseLexica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnexar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_entrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_entrada3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_entrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnexarActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        File workingDirectory = new File(System.getProperty("user.dir"));
        chooser.setCurrentDirectory(workingDirectory);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filePath = f.getAbsolutePath();
        fileName = f.getName();
        lb_entrada1.setText(fileName);
    }//GEN-LAST:event_btnAnexarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // ira apenas apagar o que foi inserido nos resultados
//        entrada.setText("");
        filePath = "";
        lb_entrada1.setText("Nome do Arquivo");
        textArea2.setText("");
        textArea3.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAnalisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisar1ActionPerformed

        //chamada do metod executar
        try{
            
            if(filePath.equals("")){
                
                textArea2.setText("ANEXE UM ARQUIVO EM JAVAZINHO PARA ANÁLISE");
                
            } else {
                
                executar(filePath);
            }
            
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_btnAnalisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
                                            
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisar1;
    private javax.swing.JButton btnAnexar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_analiseLexica1;
    private javax.swing.JLabel lb_entrada1;
    private javax.swing.JLabel lb_entrada2;
    private javax.swing.JLabel lb_entrada3;
    private javax.swing.JTextArea textArea2;
    private javax.swing.JTextArea textArea3;
    // End of variables declaration//GEN-END:variables
}
